export const BAG_BUY_ADD_ITEM = 'BAG_BUY_ADD_ITEM'
export const BAG_BUY_REMOVE_ITEM = 'BAG_BUY_REMOVE_ITEM'

export const BAG_BORROW_ADD_ITEM = 'BAG_BORROW_ADD_ITEM'
export const BAG_BORROW_REMOVE_ITEM = 'BAG_BORROW_REMOVE_ITEM'

export const BAG_SAVE_SHIPPING_ADDRESS = 'BAG_SAVE_SHIPPING_ADDRESS'
export const BAG_SAVE_PAYMENT_METHOD = 'BAG_SAVE_PAYMENT_METHOD'
export const BAG_CONFIRM_BORROW = 'BAG_CONFIRM_BORROW'


export const BAG_CLEAR_ITEMS = 'BAG_CLEAR_ITEMS'