export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDERED_ADD_REQUEST = 'ORDERED_ADD_REQUEST'
export const ORDERED_ADD_SUCCESS = 'ORDERED_ADD_SUCCESS'
export const ORDERED_ADD_FAIL = 'ORDERED_ADD_FAIL'
export const ORDERED_ADD_RESET = 'ORDERED_ADD_RESET'

export const ORDERED_LIST_MY_REQUEST = 'ORDERED_LIST_MY_REQUEST'
export const ORDERED_LIST_MY_SUCCESS = 'ORDERED_LIST_MY_SUCCESS'
export const ORDERED_LIST_MY_FAIL = 'ORDERED_LIST_MY_FAIL'
export const ORDERED_LIST_MY_RESET = 'ORDERED_LIST_MY_RESET'

export const ORDERED_LIST_REQUEST = 'ORDERED_LIST_REQUEST'
export const ORDERED_LIST_SUCCESS = 'ORDERED_LIST_SUCCESS'
export const ORDERED_LIST_FAIL = 'ORDERED_LIST_FAIL'
export const ORDERED_LIST_RESET = 'ORDERED_LIST_RESET'

export const ORDERED_DELETE_REQUEST = 'ORDERED_DELETE_REQUEST'
export const ORDERED_DELETE_SUCCESS = 'ORDERED_DELETE_SUCCESS'
export const ORDERED_DELETE_FAIL = 'ORDERED_DELETE_FAIL'
export const ORDERED_DELETE_RESET = 'ORDERED_DELETE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'



export const BORROW_CREATE_REQUEST = 'BORROW_CREATE_REQUEST'
export const BORROW_CREATE_SUCCESS = 'BORROW_CREATE_SUCCESS'
export const BORROW_CREATE_FAIL = 'BORROW_CREATE_FAIL'
export const BORROW_CREATE_RESET = 'BORROW_CREATE_RESET'

export const BORROW_DETAILS_REQUEST = 'BORROW_DETAILS_REQUEST'
export const BORROW_DETAILS_SUCCESS = 'BORROW_DETAILS_SUCCESS'
export const BORROW_DETAILS_FAIL = 'BORROW_DETAILS_FAIL'

export const BORROW_TAKE_REQUEST = 'BORROW_TAKE_REQUEST'
export const BORROW_TAKE_SUCCESS = 'BORROW_TAKE_SUCCESS'
export const BORROW_TAKE_FAIL = 'BORROW_TAKE_FAIL'
export const BORROW_TAKE_RESET = 'BORROW_TAKE_RESET'

export const BORROW_RETURN_REQUEST = 'BORROW_RETURN_REQUEST'
export const BORROW_RETURN_SUCCESS = 'BORROW_RETURN_SUCCESS'
export const BORROW_RETURN_FAIL = 'BORROW_RETURN_FAIL'
export const BORROW_RETURN_RESET = 'BORROW_RETURN_RESET'

export const BORROW_LIST_MY_REQUEST = 'BORROW_LIST_MY_REQUEST'
export const BORROW_LIST_MY_SUCCESS = 'BORROW_LIST_MY_SUCCESS'
export const BORROW_LIST_MY_FAIL = 'BORROW_LIST_MY_FAIL'
export const BORROW_LIST_MY_RESET = 'BORROW_LIST_MY_RESET'

export const BORROW_LIST_REQUEST = 'BORROW_LIST_REQUEST'
export const BORROW_LIST_SUCCESS = 'BORROW_LIST_SUCCESS'
export const BORROW_LIST_FAIL = 'BORROW_LIST_FAIL'

export const BORROW_DELETE_REQUEST = 'BORROW_DELETE_REQUEST'
export const BORROW_DELETE_SUCCESS = 'BORROW_DELETE_SUCCESS'
export const BORROW_DELETE_FAIL = 'BORROW_DELETE_FAIL'
