# Generated by Django 4.0.4 on 2022-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
