# Generated by Django 4.0.4 on 2022-06-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
