# Generated by Django 4.0.4 on 2022-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categoryName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
