# Generated by Django 4.0.4 on 2022-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='bookAuthor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='bookTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='userEmail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='userName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
